CREATE TABLE CONTACT_INFO (
    CONTACT_ID      NUMBER PRIMARY KEY,
    ADDRESS         VARCHAR2(255),
    DISTRICT        VARCHAR2(100),
    AMPHUR          VARCHAR2(100),
    PROVINCE        VARCHAR2(100),
    POSTAL_CODE     VARCHAR2(20),
    TELEPHONE       VARCHAR2(50),
    FAX             VARCHAR2(50),
    CITY            VARCHAR2(100),
    STATE           VARCHAR2(100),
    COUNTRY         VARCHAR2(100),
    CONTACT_PERSON  VARCHAR2(100),
    EMAIL           VARCHAR2(100),
    CREATED_BY      VARCHAR2(100) NOT NULL,
    CREATED_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_BY      VARCHAR2(100),
    UPDATED_DATE    TIMESTAMP
);
